### ISSUE TITLE
Provide a link to our docs on the error boundary page

### ISSUE THREAD

**Issue by alyssadai** [neurobagel/query-tool#366]
Multiple times now, we have encountered user issues with the query tool throwing out a cryptic error that looks something like this either when the app is first loaded or when a query is submitted:

```
Unexpected Application Error!
c.sort is not a function
TypeError: c.sort is not a function
    at lA (http://neurobagel.douglas.rtss.qc.ca/assets/index-ThZOToqV.js:194:8048)
    at Wp (http://neurobagel.douglas.rtss.qc.ca/assets/index-ThZOToqV.js:38:19519)
    at wf (http://neurobagel.douglas.rtss.qc.ca/assets/index-ThZOToqV.js:40:3139)
    at R1 (http://neurobagel.douglas.rtss.qc.ca/assets/index-ThZOToqV.js:40:44804)
    at w1 (http://neurobagel.douglas.rtss.qc.ca/assets/index-ThZOToqV.js:40:39766)
    at fw (http://neurobagel.douglas.rtss.qc.ca/assets/index-ThZOToqV.js:40:39694)
    at cu (http://neurobagel.douglas.rtss.qc.ca/assets/index-ThZOToqV.js:40:39547)
    at Lf (http://neurobagel.douglas.rtss.qc.ca/assets/index-ThZOToqV.js:40:35914)
    at b1 (http://neurobagel.douglas.rtss.qc.ca/assets/index-ThZOToqV.js:40:34865)
    at R (http://neurobagel.douglas.rtss.qc.ca/assets/index-ThZOToqV.js:25:1552)
```

This is not very user-friendly and can be difficult to troubleshoot both from a user's side (they most likely will not have any knowledge of React errors) and from our end, as it may require hands-on steps such as inspecting their network tab, checking what request bodies look like, etc.

It would be ideal if the query tool could catch this type of error internally, and return a more human-readable error message with some basic info on how to troubleshoot the problem (e.g., check your `NB_API_QUERY_URL` value) or at minimum, link to the docs / our "Getting help" page. 

If this kind of error is too generic/challenging to catch within the app, I think an alternative solution would be to add a section to our docs dedicated to this specific type frontend error, with troubleshooting tips / what kind of info they should collect to share with us for debugging.

**Comment by alyssadai** [comment]
@rmanaem, wdyt?

**Comment by surchs** [comment]
See also #95!
